---

- name: check nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  register: _app_nginx_conf_check
  changed_when: "_app_nginx_conf_check.rc != 0"

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: make test request to nginx
  uri:
    url: "{{ 'http://' + hostvars[inventory_hostname]['ansible_default_ipv4']['address'] + app_healthcheck_path }}"
    method: GET
    headers:
      Host: "{{ app_nginx_hostnames[0] }}"
    status_code: 200
  when:
    - app_healthcheck_enabled

- name: cleanup nginx config backups
  command: /bin/true
  notify:
    - get list of nginx config backups
    - delete old nginx config backups
  tags:
    - skip_ansible_lint

- name: get list of nginx config backups
  find:
    paths: /etc/nginx/conf.d/
    patterns: "{{ app_name }}.conf.*"
  register: _app_nginx_config_backups

- name: delete old nginx config backups
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ (_app_nginx_config_backups.files | sort(attribute='mtime',reverse=true))[app_nginx_conf_backup_retention:] }}"
  when: (_app_nginx_config_backups.files | length) > app_nginx_conf_backup_retention
