---

- name: query for dead containers
  command: docker ps -a -q -f status=dead
  register: _app_dead_containers
  changed_when: False
  tags:
    - skip_ansible_lint

- name: cleanup dead containers
  docker_container:
    name: "{{ item }}"
    force_kill: yes
    state: absent
  loop: "{{ _app_dead_containers.stdout_lines }}"
  when: _app_dead_containers.stdout
