---

- name: set facts about previous version
  set_fact:
    _prev_version: >-
      {%- if deployment_tag == _app_prev_version -%}
        {{ _app_origin_version }}
      {%- else -%}
        {{ _app_prev_version }}
      {%- endif %}

- name: store host facts
  blockinfile:
    dest: /etc/ansible/facts.d/{{ app_name }}.fact
    marker: "{mark}"
    marker_begin: '{'
    marker_end: '}'
    create: yes
    block: |
        "env_color": "{{ _app_next_color }}",
        "instances_count": "{{ app_instances_count }}",
        "version": "{{ deployment_tag }}",
        "prev_version": "{{ _prev_version }}"
          

- name: stop or remove old env containers
  docker_container:
    name: "{{ app_name }}_{{ _app_prev_color }}_{{ item }}"
    state: "{{ app_old_containers_treatment_type }}"
  loop: "{{ range(_app_prev_count | int) | list }}"
  ignore_errors: yes
  when:
    - not _app_first_run
    - deployment_tag != _app_prev_version
    - app_old_containers_treatment_enabled
