---

app_name: snappcloudapp
app_image: "vamirreza/snappcloudapp"
repo_link: "https://registry.hub.docker.com/v1/repositories/vamirreza/snappcloudapp/tags"
app_port: 3000
app_instances_count: 1
app_command: ""
app_etc_hosts: {}
app_env: {}
app_volumes: []
app_log_driver: none
app_log_options: {}
app_port_prefix: 127.0.0.1:3000

app_bluegreen_enabled: yes
app_bluegreen_default_color: 'green'
app_bluegreen_tags:
    blue:
      name: 'blue'
      port_prefix: 127.0.0.1:3001
    green:
      name: 'green'
      port_prefix: 127.0.0.1:3002
    
app_nginx_enabled: yes
app_nginx_hostnames:
    - "{{ ansible_host }}"
    
app_nginx_upstream_name: "{{ app_name }}"
app_nginx_port: 80
app_nginx_ip_hash: yes
app_nginx_crossbalance_enabled: no
app_nginx_crossbalance_hosts: "{{ ansible_play_hosts }}"
app_nginx_conf_backup_retention: 3
    
app_old_containers_treatment_enabled: yes
app_old_containers_treatment_type: absent
    
app_healthcheck_enabled: yes
app_healthcheck_path: "/healthz"
    
app_cleanup_dead_containers: yes

telegram_bot_token:
telegram_user_id: